apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: app
  labels:
    app: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
      - name: api
        image: <tu-usuario-docker>/springboot-demo:latest
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: springboot-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
